export const FETCH_UPCOMING_AND_PAST_APPOINTMENTS = 'FETCH_UPCOMING_AND_PAST_APPOINTMENTS';
export const FETCH_UPCOMING_AND_PAST_APPOINTMENTS_SUCCESS = 'FETCH_UPCOMING_AND_PAST_APPOINTMENTS_SUCCESS';
export const FETCH_UPCOMING_AND_PAST_APPOINTMENTS_FALIURE = 'FETCH_UPCOMING_AND_PAST_APPOINTMENTS_FALIURE';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_FALIURE = 'DELETE_APPOINTMENT_FALIURE';
export const MAKE_CALL_TO_TECHNICIAN = 'MAKE_CALL_TO_TECHNICIAN';
export const MAKE_CALL_TO_TECHNICIAN_SUCCESS = 'MAKE_CALL_TO_TECHNICIAN_SUCCESS';
export const MAKE_CALL_TO_TECHNICIAN_FALIURE = 'MAKE_CALL_TO_TECHNICIAN_FALIURE';
export const MESSAGE_TO_TECHNICIAN = 'MESSAGE_TO_TECHNICIAN';
export const MESSAGE_TO_TECHNICIAN_SUCCESS = 'MESSAGE_TO_TECHNICIAN_SUCCESS';
export const MESSAGE_TO_TECHNICIAN_FALIURE = 'MESSAGE_TO_TECHNICIAN_FALIURE';
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';
export const SELECT_APPOINTMENT = 'SELECT_APPOINTMENT';
export const SELECT_APPOINTMENT_SUCCESS = 'SELECT_APPOINTMENT_SUCCESS';
export const SELECT_APPOINTMENT_FALIURE = 'SELECT_APPOINTMENT_FALIURE';

