export const FETCH_UPCOMING_AND_PAST_APPOINTMENTS = 'FETCH_UPCOMING_AND_PAST_APPOINTMENTS';
export const FETCH_UPCOMING_AND_PAST_APPOINTMENTS_SUCCESS = 'FETCH_UPCOMING_AND_PAST_APPOINTMENTS_SUCCESS';
export const FETCH_UPCOMING_AND_PAST_APPOINTMENTS_FALIURE = 'FETCH_UPCOMING_AND_PAST_APPOINTMENTS_FALIURE';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_FALIURE = 'DELETE_APPOINTMENT_FALIURE';
