export const FETCH_AUTH_USER_DETAILS = 'FETCH_AUTH_USER_DETAILS';
export const FETCH_AUTH_USER_DETAILS_SUCCESS = 'FETCH_AUTH_USER_DETAILS_SUCCESS';
export const FETCH_AUTH_USER_DETAILS_FAILURE = 'FETCH_AUTH_USER_DETAILS_FAILURE';
