export const POST_NEW_APPOINTMENT = 'POST_NEW_APPOINTMENT';
export const POST_NEW_APPOINTMENT_SUCCESS = 'POST_NEW_APPOINTMENT_SUCCESS';
export const POST_NEW_APPOINTMENT_FALIURE = 'POST_NEW_APPOINTMENT_FALIURE';
export const SCHEDULE_NEW_APPOINTMENT = 'SCHEDULE_NEW_APPOINTMENT';
export const SCHEDULE_NEW_APPOINTMENT_SUCCESS = 'SCHEDULE_NEW_APPOINTMENT_SUCCESS';
export const SCHEDULE_NEW_APPOINTMENT_FALIURE = 'SCHEDULE_NEW_APPOINTMENT_FALIURE';
export const STORE_APPOINTMENT_SCHEDULE = 'STORE_APPOINTMENT_SCHEDULE';

