export const POST_NEW_APPOINTMENT = 'POST_NEW_APPOINTMENT';
export const POST_NEW_APPOINTMENT_SUCCESS = 'POST_NEW_APPOINTMENT_SUCCESS';
export const POST_NEW_APPOINTMENT_FALIURE = 'POST_NEW_APPOINTMENT_FALIURE';
export const SCHEDULE_NEW_APPOINTMENT = 'SCHEDULE_NEW_APPOINTMENT';
export const SCHEDULE_NEW_APPOINTMENT_SUCCESS = 'SCHEDULE_NEW_APPOINTMENT_SUCCESS';
export const SCHEDULE_NEW_APPOINTMENT_FALIURE = 'SCHEDULE_NEW_APPOINTMENT_FALIURE';
export const STORE_APPOINTMENT_SCHEDULE = 'STORE_APPOINTMENT_SCHEDULE';
export const USER_CARD_DETAILS = 'USER_CARD_DETAILS';
export const USER_CARD_DETAILS_SUCCESS = 'USER_CARD_DETAILS_SUCCESS';   
export const ADD_NEW_CARD_DETAILS = 'ADD_NEW_CARD_DETAILS';
export const ADD_NEW_CARD_DETAILS_SUCCESS = 'ADD_NEW_CARD_DETAILS_SUCCESS';
export const ADD_NEW_CARD_DETAILS_FALIURE = 'ADD_NEW_CARD_DETAILS_FALIURE';
export const HIDE_ALERT = 'HIDE_ALERT';
export const STORE_USER_SELECTED_CARD_DETAILS = 'STORE_USER_SELECTED_CARD_DETAILS';
export const HIDE_SCHEDULE_ALERT = 'HIDE_SCHEDULE_ALERT';

