export const SEARCH_ADDRESS = 'SEARCH_ADDRESS';
export const SEARCH_ADDRESS_SUCCESS = 'SEARCH_ADDRESS_SUCCESS';
export const SEARCH_ADDRESS_FALIURE = 'SEARCH_ADDRESS_FALIURE';
export const EMPTY_FEATURES = 'EMPTY_FEATURES';
