export const SEARCH_ADDRESS = 'SEARCH_ADDRESS';
export const SEARCH_ADDRESS_SUCCESS = 'SEARCH_ADDRESS_SUCCESS';
export const SEARCH_ADDRESS_FALIURE = 'SEARCH_ADDRESS_FALIURE';
export const EMPTY_FEATURES = 'EMPTY_FEATURES';
export const GET_FULL_ADDRESS_REVERSE_GEO = 'GET_FULL_ADDRESS_REVERSE_GEO';
export const GET_FULL_ADDRESS_REVERSE_GEO_SUCCESS = 'GET_FULL_ADDRESS_REVERSE_GEO_SUCCESS';
export const GET_FULL_ADDRESS_REVERSE_GEO_FALIURE = 'GET_FULL_ADDRESS_REVERSE_GEO_FALIURE';
