export const FETCH_SERVICES = 'FETCH_SERVICES';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FALIURE = 'FETCH_SERVICES_FALIURE';
export const CREATE_NEW_USER_SERVIVE_APPOINTMENT = 'CREATE_NEW_USER_SERVIVE_APPOINTMENT';
export const SERVICES_APPOINTMENT_SUCCESS = 'SERVICES_APPOINTMENT_SUCCESS';
export const SERVICES_APPOINTMENT_FALIURE = 'SERVICES_APPOINTMENT_FALIURE';
export const HIDE_ALERT = 'HIDE_ALERT';
