export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const RESET_PASSWORD_MAIL_SENT = 'RESET_PASSWORD_MAIL_SENT';
export const RESET_PASSWORD_MAIL_ERROR = 'RESET_PASSWORD_MAIL_ERROR';
export const HIDE_ALERT = 'HIDE_ALERT';
export const HIDE_RESET_ALERT = 'HIDE_RESET_ALERT';
export const SAVE_DEVICE_TOKEN = 'SAVE_DEVICE_TOKEN';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGIN_THROUGH_ACCESS_TOKEN = 'LOGIN_THROUGH_ACCESS_TOKEN';
export const LOGIN_THROUGH_ACCESS_TOKEN_SUCCESS = 'LOGIN_THROUGH_ACCESS_TOKEN_SUCCESS';
export const LOGIN_THROUGH_ACCESS_TOKEN_FAILURE = 'LOGIN_THROUGH_ACCESS_TOKEN_FAILURE';
  
