export const FETCH_NEARBY_PLACES = 'FETCH_NEARBY_PLACES';
export const FETCH_NEARBY_PLACES_SUCCESS = 'FETCH_NEARBY_PLACES_SUCCESS';
export const FETCH_NEARBY_PLACES_FALIURE = 'FETCH_NEARBY_PLACES_FALIURE';
