export const FETCH_NEARBY_SERVICE_PROVIDERS = 'FETCH_NEARBY_SERVICE_PROVIDERS';
export const FETCH_NEARBY_SERVICE_PROVIDERS_SUCCESS = 'FETCH_NEARBY_SERVICE_PROVIDERS_SUCCESS';
export const FETCH_NEARBY_SERVICE_PROVIDERS_FALIURE = 'FETCH_NEARBY_SERVICE_PROVIDERS_FALIURE';
export const FETCH_POLYGON_DATA = 'FETCH_POLYGON_DATA';
export const FETCH_POLYGON_DATA_SUCCESS = 'FETCH_POLYGON_DATA_SUCCESS';
export const FETCH_POLYGON_DATA_FALIURE = 'FETCH_POLYGON_DATA_FALIURE';
export const EMPTY_POLYGON_DATA = 'EMPTY_POLYGON_DATA';
