export const FETCH_RECENT_LOCATIONS = 'FETCH_RECENT_LOCATIONS';
export const FETCH_RECENT_LOCATIONS_SUCCESS = 'FETCH_RECENT_LOCATIONS_SUCCESS';
export const FETCH_RECENT_LOCATIONS_FAILURE = 'FETCH_RECENT_LOCATIONS_FAILURE';
export const HIDE_ALERT = 'HIDE_ALERT';
export const DELETE_RECENT_LOCATION = 'DELETE_RECENT_LOCATION';
export const DELETE_RECENT_LOCATION_SUCCESS = 'DELETE_RECENT_LOCATION_SUCCESS';
export const DELETE_RECENT_LOCATION_FAILURE = 'DELETE_RECENT_LOCATION_FAILURE';
