export const FETCH_PROMO_CODE = 'FETCH_PROMO_CODE';
export const FETCH_PROMO_CODE_SUCCESS = 'FETCH_PROMO_CODE_SUCCESS';
export const FETCH_PROMO_CODE_FAILURE = 'FETCH_PROMO_CODE_FAILURE';
export const HIDE_ALERT = 'HIDE_ALERT';
export const USE_PROMO_CODE_BY_USER = 'USE_PROMO_CODE_BY_USER';
export const USE_PROMO_CODE_BY_USER_SUCCESS = 'USE_PROMO_CODE_BY_USER_SUCCESS';
export const USE_PROMO_CODE_BY_USER_FAILURE = 'USE_PROMO_CODE_BY_USER_FAILURE';
