export const FETCH_ALL_USER_VEHICLES = 'FETCH_ALL_USER_VEHICLES';
export const FETCH_ALL_USER_VEHICLES_SUCCESS = 'FETCH_ALL_USER_VEHICLES_SUCCESS';
export const FETCH_ALL_USER_VEHICLES_FALIURE = 'FETCH_ALL_USER_VEHICLES_FALIURE';
